import {
  SITE_URL,
  SITE_NAME,
  SITE_TITLE,
  SITE_DESCRIPTION,
  OG_IMAGE,
} from "./site";

export const NAV_SECTIONS = [
  { id: "home", name: "Home" },
  { id: "about", name: "About" },
  { id: "projects", name: "Projects" },
  { id: "education", name: "Education" },
  { id: "work", name: "Work" },
  { id: "skills", name: "Skills" },
  { id: "testimonials", name: "Testimonials" },
  { id: "contact", name: "Contact" },
];

export const personSchema = {
  "@context": "https://schema.org",
  "@type": "Person",
  "@id": `${SITE_URL}/#person`,
  name: SITE_NAME,
  url: SITE_URL,
  image: OG_IMAGE,
  jobTitle: "Freelance Web & App Developer",
  description: SITE_DESCRIPTION,
  address: {
    "@type": "PostalAddress",
    addressLocality: "Haridwar",
    addressRegion: "Uttarakhand",
    addressCountry: "IN",
  },
  sameAs: [
    "https://github.com/kartikeysharmaks",
    "https://www.linkedin.com/in/kartikeysharmaks/",
    "https://www.instagram.com/kartikeysharmaks/",
    "https://www.facebook.com/kartikeysharma1616",
  ],
  knowsAbout: [
    "React",
    "Next.js",
    "Node.js",
    "React Native",
    "TypeScript",
    "MongoDB",
    "Sanity CMS",
    "Web Development",
    "Mobile Development",
    "Full Stack Development",
    "Freelance Website Developer",
    "Freelance React Developer",
    "Freelance React Native Developer",
    "Freelance Next.js Developer",
    "Freelance Node.js Developer",
    "Freelance MERN Developer",
    "Freelance MongoDB Developer",
    "Freelance Sanity CMS Developer",
    "Freelance Developer",
    "Full Stack Developer",
    "MERN Stack Developer",
    "MEAN Stack Developer",
    "Software Developer",
    "E-commerce Developer",
    "Web App Developer",
    "Mobile App Developer",
    "Cross Platform App Developer",
    "Progressive Web App Developer",
    "Freelance E-commerce Developer",
    "Freelance Web App Developer",
    "Freelance Mobile App Developer",
    "Freelance Cross Platform App Developer",
    "Freelance Progressive Web App Developer",
    "Freelance Software Developer",
    "Software Engineer",
    "Freelance Software Engineer",
    "AI Website Development",
    "Vibe Coding",
    "AI-Assisted Web Design",
    "Custom Web Applications",
  ],
};

export const websiteSchema = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  "@id": `${SITE_URL}/#website`,
  name: SITE_TITLE,
  url: SITE_URL,
  description: SITE_DESCRIPTION,
  inLanguage: "en",
  publisher: { "@id": `${SITE_URL}/#person` },
};

export const profilePageSchema = {
  "@context": "https://schema.org",
  "@type": "ProfilePage",
  "@id": `${SITE_URL}/#webpage`,
  url: SITE_URL,
  name: SITE_TITLE,
  description: SITE_DESCRIPTION,
  isPartOf: { "@id": `${SITE_URL}/#website` },
  about: { "@id": `${SITE_URL}/#person` },
  primaryImageOfPage: { "@type": "ImageObject", url: OG_IMAGE },
  inLanguage: "en",
};

export const professionalServiceSchema = {
  "@context": "https://schema.org",
  "@type": "ProfessionalService",
  "@id": `${SITE_URL}/#service`,
  name: "Kartikeysharmaks - Freelance Web & App Developer",
  url: SITE_URL,
  image: OG_IMAGE,
  description: SITE_DESCRIPTION,
  priceRange: "$$",
  address: {
    "@type": "PostalAddress",
    addressLocality: "Haridwar",
    addressRegion: "Uttarakhand",
    addressCountry: "IN",
  },
  areaServed: ["Worldwide", "India"],
  hasMap: "https://www.google.com/maps/search/?api=1&query=Kartikeysharmaks+-+Freelance+Web+%26+App+Developer",
  sameAs: [
    "https://www.google.com/search?q=Kartikeysharmaks+-+Freelance+Web+%26+App+Developer",
    "https://github.com/kartikeysharmaks",
    "https://www.linkedin.com/in/kartikeysharmaks/",
    "https://www.facebook.com/kartikeysharma1616",
    "https://www.instagram.com/kartikeysharmaks/",
  ],
  serviceType: [
    "Web Development",
    "AI Website Development",
    "Vibe Coding",
    "Mobile App Development",
    "Full Stack Development",
    "Custom Web Applications",
  ],
  identifier: {
    "@type": "PropertyValue",
    name: "Google Business Store Code",
    value: "09553991736879594017",
  },
};

export const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: NAV_SECTIONS.map((section, index) => ({
    "@type": "ListItem",
    position: index + 1,
    name: section.name,
    item: `${SITE_URL}/#${section.id}`,
  })),
};

export const jsonLdGraph = {
  "@context": "https://schema.org",
  "@graph": [
    personSchema,
    websiteSchema,
    profilePageSchema,
    professionalServiceSchema,
    breadcrumbSchema,
  ],
};
